openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - url: http://http://3.208.194.127:8000/api/v1/
    description: WWU Class Server
info:
  description: |
    Review the details of the assignment in your lab project README.md file.
  version: "1.0.0"
  title: Final Project CPTR320 Anglene lake
tags:
  - name: WWU Intramurals
paths:
  /Teams:
    post:
      tags:
        - Team
      summary: Add a new Team
      responses:
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/schemas/Team'
    get:
      tags:
        - Team
      summary: Finds Teams
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
  /Teams/{id}:
    get:
      tags:
        - Team
      summary: Finds Team by id
      parameters:
        - name: id
          in: path
          description: ID of Team to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '400':
          description: Invalid ID value
        '404':
          description: Team not found
    put:
      tags:
        - Team
      summary: Updates a list
      parameters:
        - name: id
          in: path
          description: ID of Team that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/schemas/Team'
    delete:
      tags:
        - Team
      summary: Deletes a list
      parameters:
        - name: id
          in: path
          description: Team id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: List not found

  /Players:
    post:
      tags:
        - Player
      summary: Add a new Player
      responses:
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/Player'
    get:
      tags:
        - Player
      summary: Finds Players
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
  /Players/{id}:
    get:
      tags:
        - Player
      summary: Finds Player by id
      parameters:
        - name: id
          in: path
          description: ID of Player to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '400':
          description: Invalid ID value
        '404':
          description: Player not found
    put:
      tags:
        - Player
      summary: Updates a list
      parameters:
        - name: id
          in: path
          description: ID of Player that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/Player'
    delete:
      tags:
        - Player
      summary: Deletes a list
      parameters:
        - name: id
          in: path
          description: Player id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: List not found  
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        preferred_name:
          type: string
        email:
          type: string
    Player:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        preferred_name:
          type: string
        email:
          type: string
        graduation_year:
          type: integer
          format: int64
        birth_date:
          type: string
  requestBodies:
    Teams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Team'
      description: Team object that needs to be added
      required: true
    Player:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Player'
      description: Player object that needs to be added
      required: true